### ISSUE TITLE
how to test and develop locally

### ISSUE THREAD

**Issue by james-powis** [netbox-community/netbox-animal-sounds#4]
Are there any recommendations for how to develop locally and test without involving or impacting a full install (potentially production) of netbox?

**Comment by lvrfrc87** [comment]
@james-powis I use a local copy of `netbox-docker`. I edited the `docker-compose.yml` file where I mount a local `plugin` into `netbox`. From there, I do my development work: I first define a plugin and run `setup.py` in dev mode. Then I enable the plugin under `configuration.py`. Once the plugin is recognized by netbox, I keep doing my work. Every time I change something I restart `netbox` and `netbox-worker`

**Comment by blgo** [comment]
> @james-powis I use a local copy of `netbox-docker`. I edited the `docker-compose.yml` file where I mount a local `plugin` folder into `netbox`. From there, I do my development work: I first define a plugin and run `setup.py` in dev mode. Then I enable the plugin under `configuration.py`. Once the plugin is recognized by netbox, I keep doing my work. Every time I change something I restart `netbox` and `netbox-worker`
> 
> Here my test work: https://github.com/lvrfrc87/netbox-docker
> 
> Hope this can help

I couln't get your example working... 
```
 export VERSION=v2.9.4                                                                     
./build.sh $VERSION
docker-compose up -d
```

Log:
```
django.core.exceptions.ImproperlyConfigured: Unable to import plugin netbox_vespa_plugin: Module not found. Check that the plugin module has been installed within the correct Python environment.
```

**Comment by lvrfrc87** [comment]
You need to install manually as I have not created any pip package

https://netbox.readthedocs.io/en/stable/plugins/#installing-plugins

**Comment by blgo** [comment]
I could install plugins using the Dockerfile and README instructions from this plugin: https://github.com/iDebugAll/nextbox-ui-plugin
