### ISSUE TITLE
Python package name doesn't match Django App name

### ISSUE THREAD

**Issue by cpmills1975** [netbox-community/netbox-animal-sounds#8]
Perhaps this is a circumstance of my workflow, and I appreciate the sample app has no place in production, but I have an Ansible playbook to deploy netbox-docker and include within that, my plugins and (for sanity checking - i.e. to make sure the process works) netbox-animal-sounds.

From the list of plugins I provide, Ansible generates a docker-compose.yml file, that 'pip install's them during build. The PLUGINS line in NetBox's configuration.py file is (was) formed from the same list of plugins, but because the python package name in setup.py is different to the Django app name in __init__.py, I need to pip install netbox-animal-sounds and add netbox_animal_sounds to my configuration.py. This is both confusing and makes automation more challenging.

It would help my automation, and support those learning to write Django apps (not least me) if both the python package name and the Django app name matched (used the same word separator).

**Comment by steffann** [comment]
Pip is smart enough to deal with this. The following commands do the same thing:

```
pip install netbox_animal_sounds 
pip install netbox-animal-sounds
```

So you can use underscores everywhere and it will work fine. As far as I know the convention is to use dashes in pypi package names and underscores in python package names. Pip will figure out the right package name when you use underscores.

**Comment by cpmills1975** [comment]
OK, that's somewhat helpful. Presumably it isn't clever enough when using develop mode?  I'm using pip install -e /path/to/plugin as (apart from this being dev and my plugin source being local) my plugins are being developed for internal use only so will be unlikely to be published to PyPi.

The Ansible template I'm using to generate the Dockerfile contains:

```
COPY plugins /netbox/plugins
{% for plugin in netbox_plugins %}
    {%- if loop.first %}RUN {% endif %}pip install -e /netbox/plugins/{{ plugin }} {% if not loop.last %}&& {% endif %}
{% endear %}
```

to generate something similar to:

```
COPY plugins /netbox/plugins
RUN pip install -e /netbox/plugins/my_plugin && pip install -e /netbox/plugins/netbox-animal-sounds
```

**Comment by steffann** [comment]
I'm sure your scripts can replace the `-` with `_` where appropriate :)
